protection : "test xor key"
launcher_version : "Test version"
clients_path : "clients"
launcher_path:
  generic: "launcher.jar"
  win32: "launcher.exe"
  win64: "launcher.exe"
skins:
  default: default_skin.png
  directory: skins
ignore_regex: "\\.(config|cfg|points|properties)$"
