protection : "test xor key"
launcher_version : "Test version"
clients_path : "public/clients"
launcher_path:
  generic: "launcher.jar"
  win32: "launcher.exe"
  win64: "launcher.exe"
skins:
  default: default_skin.png
  directory: skins
ignore_regex: "\\.(?:(?!so|dylib|dll|jar|litemod).)$"
