protection : "hellish"
launcher_version : "0.1.4"
clients_path : "public/clients"
launcher_path:
  generic: "launcher.jar"
  win32: "launcher.exe"
  win64: "launcher.exe"
skins:
  default: default_skin.png
  directory: skins
ignore_regex: ".*\\.(json|config|points|world|cfg|txt|dat|properties|ini)$"
skin_dimensions:
  - width : 64
    height: 32
  - width : 64
    heigth: 64

cape_dimensions:
  - width : 64
    height: 32
  - width : 22
    height: 17
